name: bench
'on':
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - '**.tsx'
      - '**.jsx'
      - '**.yml'
      - '**.json'

jobs:
  bench:
    name: 'Benchmark'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Deno
        uses: denoland/setup-deno@v1
      - name: Install Bun
        uses: antongolub/action-setup-bun@v1.4.0
      - name: Update Bun
        run: bun upgrade --canary
        name: Install oha
      - uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/hatoo/oha/releases/download/v0.5.4/oha-linux-amd64'
          name: 'oha'
      - name: Install modules
        run: yarn install
      - name: Run benchmarks
        run: yarn start
